# Generated by Django 3.0.8 on 2020-07-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(max_length=200)),
                ('containing_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contained_location', to='journal.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
                ('date', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Location')),
            ],
        ),
    ]
