# Generated by Django 3.0.8 on 2020-07-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
