# Generated by Django 3.0.8 on 2020-07-19 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='containing_location',
        ),
        migrations.AddField(
            model_name='location',
            name='parent_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_location', to='journal.Location'),
        ),
    ]
