# Generated by Django 3.0.8 on 2020-08-02 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20200719_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='journal.Location'),
        ),
    ]
